=== plowed/MASTER/Semestre 2/BDA/TP2/ex2/univ.dtd
<!ELEMENT universite (enseignants?,etudiants?,listecours?,matieres?,salles?)>
  <!ELEMENT enseignants (enseignant+)>
  <!ELEMENT etudiants (etudiant+)>
  <!ELEMENT listecours (cours+)>
  <!ELEMENT matieres (matiere+)>
  <!ELEMENT salles (salle+)>
  <!ELEMENT enseignant (#PCDATA)>
	<!ATTLIST enseignant id_matiere IDREFS #REQUIRED>
	<!ATTLIST enseignant id_cours IDREFS #REQUIRED>
  <!ELEMENT cours (code, titre)>
	<!ATTLIST cours id ID #REQUIRED>
	<!ATTLIST cours id_salle IDREF #REQUIRED>
  <!ELEMENT salle EMPTY>
    <!ATTLIST salle id ID #IMPLIED>
    <!ATTLIST salle numero CDATA #REQUIRED>
  <!ELEMENT nom (#PCDATA) >
  <!ELEMENT matiere (#PCDATA) >
	<!ATTLIST matiere id_matiere ID #REQUIRED>
  <!ELEMENT titre (#PCDATA) >
  <!ELEMENT numero (#PCDATA) >
  <!ELEMENT code (#PCDATA) >
  <!ELEMENT etudiant (nom,numero)>
	<!ATTLIST etudiant id_cours IDREFS #REQUIRED>

=== plowed/MASTER/Semestre 2/BDA/TP2/ex2/univQ2.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE universite SYSTEM "univ.dtd">


<universite>
	<enseignants>
		<enseignant id_matiere="m1 m2" id_cours="c1 c2">Toto</enseignant>
		<enseignant id_matiere="m1 m2" id_cours="c1 c2">Titi</enseignant>
	</enseignants>
	<etudiants>
		<etudiant id_cours="c1 c2">
			<nom>Tata</nom>
			<numero>123</numero>
		</etudiant>
	</etudiants>
	<listecours>
		<cours id="c1" id_salle="s1">
			<code>LI345</code>
			<titre>bases de données et sites Web</titre>
		</cours>
		<cours id="c2" id_salle="s2">
			<code>LI349</code>
			<titre>compilation</titre>
		</cours>
	</listecours>
	<matieres>
		<matiere id_matiere="m1">bases de données</matiere>
		<matiere id_matiere="m2">langage</matiere>
	</matieres>
	<salles>
		<salle id="s1" numero="Amphi B1"/>
		<salle id="s2" numero="Amphi B2"/>
	</salles>
</universite>
