=== plowed/MASTER/Semestre 2/BDA/TP3/README.dtd
<!ELEMENT td-tp (numero-td,binome,exercices)>
	<!ELEMENT numero-td (#PCDATA)>
	<!ELEMENT binome (#PCDATA)>
	<!ELEMENT exercices (exercice+)>
		<!ELEMENT exercice (question+)>
			<!ATTLIST exercice numero CDATA #REQUIRED>
			<!ELEMENT question (#PCDATA|liste|nouvelleLigne)*>
				<!ATTLIST question numero CDATA #REQUIRED>
				<!ELEMENT liste (item+)>
					<!ELEMENT item (#PCDATA|liste|nouvelleLigne)*>
				<!ELEMENT nouvelleLigne EMPTY>

=== plowed/MASTER/Semestre 2/BDA/TP2/README.xml
<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet href="README.css" type="text/css"?>

<!DOCTYPE td-tp SYSTEM "README.dtd">
<td-tp>
	<numero-td>2</numero-td>
	<binome>
		VINCENT Thomas et DRUEL Damien
	</binome>
	<exercices>
		<exercice numero="1">
			<question numero="1">
				<liste>
					<item>d1.dtd :
						<liste>
							<item>a1.xml est validé par d1.dtd</item>
							<item>a2.xml est validé par d1.dtd</item>
							<item>a3.xml n'est validé par d1.dtd car il n'y as pas une balise F qui suit une balise B ou D</item>
						</liste>
					</item>
					<item>d2.dtd :
						<liste>
							<item>a1.xml n'est pas validé par d2.dtd car il n'y a pas de balise D qui suit la balise B</item>
							<item>a2.xml est validé par d2.dtd</item>
							<item>a3.xml est validé par d2.dtd</item>
						</liste>
					</item>
					<item>d3.dtd :
						<liste>
							<item>a1.xml n'est pas validé par d3.dtd car il n'y a pas au moin une balise D qui suit la balise B</item>
							<item>a2.xml est validé par d3.dtd</item>
							<item>a3.xml n'est pas validé par d3.dtd car il n'y a pas une succession de balise B puis une succession de balise D mais une succession de balise B, D</item>
						</liste>
					</item>
				</liste>
			</question>
		</exercice>
		<exercice numero="2">
			<question numero="1">
				Le fichier univ.xml n'est pas valide car d'aprés le fichier univ.dtd la balise salle n'as aucun contenu or ici elle contient une balise contenant le numero de salle. De plus dans le fichier univ.dtd la racine est défini sans majuscule alors qu'elle en comporte dans le fichier univ.xml et une des balise code n'est pas bien fermé.
				<nouvelleLigne/>
				cf : fichier ex2/univQ1.xml
			</question>
			<question numero="2">
				Pour prendre en compte les informations, il a fallu rajouter des balises permettant de regrouper les enseignants, les étudiants, les matiéres, les cours et les salles. Les cours, les matiéres et les salles possédent des identifiants. Les enseignants, les étudiants et les cours font références à ces identifiants. Mais un défaut du DTD est que l'on ne peut pas par exemple définir que l'attribut id_salle de la balise cours fait référence à l'attribut id de la balise salle. On peut donc, par exemple, y faire référence à l'attribut id_matiere de la balise matiere.
				<nouvelleLigne/>
				cf : fichier ex2/univQ2.xml et ex2/univ.dtd
			</question>
		</exercice>
		<exercice numero="3">
			<question numero="1">
				cf : fichier ex3/transpole.xml et ex3/transpole.dtd
			</question>
			<question numero="2">
				Lors de la création du DTD on remarque qu'un certain nombre d'information pourrai être regrouper, par exemple l'attribut surface-m2 qui se retrouve dans plusieurs. Mais aucun regroupement n'est possible avec le DTD ce qui en est une limite.
				<nouvelleLigne/>
				cf : fichier ex3/maisons.xml et ex3/maisons.dtd
			</question>
		</exercice>
		<exercice numero="4">
			<question numero="1">
				cf : fichier ex4/famille.dtd
			</question>
		</exercice>
	</exercices>
</td-tp>

=== plowed/MASTER/Semestre 2/BDA/TP3/README.xml
<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet href="README.css" type="text/css"?>

<!DOCTYPE td-tp SYSTEM "README.dtd">
<td-tp>
	<numero-td>3</numero-td>
	<binome>
		VINCENT Thomas et DRUEL Damien
	</binome>
	<exercices>
		<exercice numero="1">
			<question numero="1">
				<liste>
					<item> les producteurs de fruits :
						<liste>
							<item>/descendant::producteur</item>
							<item>//producteur</item>
						</liste>
					</item>
					<item> les légumes produits en Espagne :
						<liste>
							<item>//descendant::legume[origine="Espagne"]/producteur</item>
							<item>//legume[origine="Espagne"]/producteur</item>
						</liste>
					</item>
					<item> les origines des clémentines de calibre 1 issues de l’agriculture biologique :
						<liste>
							<item>/descendant::fruit[@type="clementine" and @calibre="1" and bio]/origine</item>
							<item>//fruit[@type="clementine" and @calibre="1" and bio]/origine</item>
						</liste>
					</item>
					<item> les producteurs bretons :
						<liste>
							<item>/descendant::*[origine/@region="Bretagne"]/producteur</item>
							<item>//*[origine/@region="Bretagne"]/producteur</item>
						</liste>
					</item>
				</liste>
			</question>
		</exercice>
		<exercice numero="2">
			<question numero="2">
				<liste>
					<item> recette1.xml :
						<liste>
							<item>Les éléments titres des recettes : //titre</item>
							<item>Les noms des ingrédients : //nom_ing</item>
							<item>L’élément titre de la deuxième recette : //recette[2]/titre</item>
							<item>La dernière étape de chaque recette : //texte/etape[last()]</item>
							<item>Le nombre de recettes : count(//recette)</item>
							<item>Les éléments recette qui ont strictement moins de 7 ingrédients : //recette[count(ingredients/ingredient)&lt;7]</item>
							<item>Les titres des recettes qui ont strictement moins de 7 ingrédients : //recette[count(ingredients/ingredient)&lt;7]/titre</item>
							<item>Les recettes qui utilisent de la farine : //recette[contains(ingredients//nom_ing,"farine")]</item>
							<item>Les recettes de la catégorie entrée : //recette[contains(./categorie,"entrée")]</item>
						</liste>
					</item>
					<item> recette2.xml :
						<liste>
							<item>Les éléments titres des recettes : //titre</item>
							<item>Les noms des ingrédients : //ingredient</item>
							<item>L’élément titre de la deuxième recette : //recette[2]/titre</item>
							<item>La dernière étape de chaque recette : //texte/etape[last()]</item>
							<item>Le nombre de recettes : count(//recette)</item>
							<item>Les éléments recette qui ont strictement moins de 7 ingrédients : //recette[count(ingredients/ing-recette)&lt;7]</item>
							<item>Les titres des recettes qui ont strictement moins de 7 ingrédients : //recette[count(ingredients/ing-recette)&lt;7]/titre</item>
							<item>Les recettes qui utilisent de la farine : //recette[contains(ingredients//@ingredient,"farine")]</item>
							<item>Les recettes de la catégorie entrée : //recette[contains(@categ,"entree")]</item>
						</liste>
					</item>
				</liste>
			</question>
		</exercice>
		<exercice numero="3">
			<question numero="1">
				<liste>
					<item>Le nombre de morceaux (tracks hors PlayLists) de la bibliothèque : count(//key[.="Tracks"]/following-sibling::dict/dict)</item>
					<item>Tous les noms d’albums : //key[.="Album"]/following-sibling::string[1]</item>
					<item>Tous les genres de musique (Jazz, Rock, . . .) : //key[.="Genre"]/following-sibling::string[1]</item>
					<item>Le nombre de morceaux de Jazz : count(//key[.="Genre" and ./following-sibling::string[1] = "Jazz"])</item>
					<item>Tous les genres de musique mais en faisant en sorte de n’avoir dans le résultat qu’une seule occurrence de chaque genre : //key[.="Genre"]/following-sibling::string[position()=1 and not(../preceding-sibling::dict/key[.="Genre"]/following-sibling::string[1]=.)]</item>
					<item>Le titre (Name) des morceaux qui ont été écoutés au moins 1 fois : //key[.="Play Count"]/following-sibling::integer[position()=1 and .>0]/parent::dict/key[.="Name"]/following-sibling::string[1]</item>
					<item>Le titre des morceaux qui n’ont jamais été écoutés : //key[.="Play Count"]/following-sibling::integer[position()=1 and .=0]/parent::dict/key[.="Name"]/following-sibling::string[1] | //key[.="Tracks"]/following-sibling::dict/dict[not(./key[.="Play Count"])]/key[.="Name"]/following-sibling::string[1]</item>
					<item>Le titre du (ou des) morceaux les plus anciens de la bibliothèque</item>
				</liste>
			</question>
		</exercice>
	</exercices>
</td-tp>
